name: Test Versioning GitHub
on: [label, push]

defaults:
  run:
    working-directory: TestGitHubActions

jobs:
  update-version-number:
    # name: Test Versioning GitHub
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Test stuff"
        # shell: bash
        run: |
          value = cat ".env"
          echo "$value"

        # run: echo "$value"
