name: Test Versioning GitHub
on: [label, push]

jobs:
  update-version-number:
    # name: Test Versioning GitHub
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v3

      - name: "Test stuff"
        # shell: bash
        run: |
          sudo apt-get -y install coreutils
          cat ".env"
          # compgen -c

        # run: echo "$value"
